import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bone: '#F4F3F0',
        paper: '#FFFFFF',
        ink: '#16181C',
        'ink-soft': '#5C5F66',
        'ink-faint': '#8C8F95',
        taupe: '#9C9487',
        stone: '#CCC8C1',
        'stone-light': '#E1DED9',
        navy: '#1E2B3C',
        brand: {
          primary: '#16181C',
          secondary: '#5C5F66',
          accent: '#9C9487',
          light: '#F4F3F0',
          white: '#FFFFFF',
        },
        business: {
          navy: '#1E2B3C',
          gold: '#9C9487',
          cream: '#F4F3F0',
          charcoal: '#16181C',
          slate: '#5C5F66',
          darkNavy: '#1E2B3C',
        },
      },
      borderRadius: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      fontFamily: {
        sans: ['Inter Tight', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif'],
        serif: ['Inter Tight', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif'],
        heading: ['Inter Tight', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-1': ['clamp(2.375rem, 6.4vw, 4.25rem)', { lineHeight: '1.02', letterSpacing: '-0.035em', fontWeight: '200' }],
        'display-2': ['clamp(2rem, 4.8vw, 3rem)', { lineHeight: '1.05', letterSpacing: '-0.035em', fontWeight: '200' }],
        'h1': ['clamp(1.75rem, 3.2vw, 2.5rem)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '300' }],
        'h2': ['clamp(1.5rem, 2.8vw, 2rem)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '300' }],
        'h3': ['clamp(1.25rem, 2vw, 1.5rem)', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '300' }],
        'h4': ['1.125rem', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-lg': ['clamp(1.0625rem, 1.5vw, 1.1875rem)', { lineHeight: '1.65', fontWeight: '300' }],
        'body': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'eyebrow': ['0.625rem', { lineHeight: '1.4', letterSpacing: '0.18em', fontWeight: '500' }],
      },
      boxShadow: {
        none: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        card: 'none',
        soft: 'none',
        lifted: 'none',
      },
      maxWidth: {
        'measure': '640px',
        'measure-wide': '720px',
        'content': '1280px',
      },
    },
  },
  plugins: [],
};
export default config;
